# Generated by Django 4.1.1 on 2022-09-22 08:55

from django.db import migrations, models
import django.db.models.deletion
import home_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('home_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(default='Guest', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.ForeignKey(default=home_api.models.User.get_default, on_delete=django.db.models.deletion.SET_DEFAULT, to='home_api.groups'),
        ),
    ]
