# Generated by Django 4.1.1 on 2022-09-21 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_api', '0002_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='date',
            field=models.DateField(auto_created=True, auto_now=True),
        ),
    ]
