# Generated by Django 4.1.1 on 2022-09-22 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_api', '0002_groups_user_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='date',
            field=models.DateField(),
        ),
    ]
