# Generated by Django 4.1.1 on 2022-09-21 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_api', '0003_alter_check_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
